name: Android Bash Build

on:
  workflow_dispatch:
    inputs:
      API_LEVEL:
        description: 'Select the API Level for the build'
        required: true
        default: '28'
        type: string

env:
  NDK_VERSION: "27.2.12479018"
  ANDROID_BUILD_DIR: "${{ github.workspace }}/android_build"
  NDK_INSTALL_DIR: "${{ github.workspace }}/android-ndk"  # 修改安装目录到工作空间

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Android NDK
      run: |
        NDK_ZIP="android-ndk-r27b-linux.zip"
        # 下载到工作空间目录
        wget -q https://dl.google.com/android/repository/${NDK_ZIP} -P "${{ env.NDK_INSTALL_DIR }}"
        # 创建目标目录并解压
        mkdir -p "${{ env.NDK_INSTALL_DIR }}"
        unzip -q "${{ env.NDK_INSTALL_DIR }}/${NDK_ZIP}" -d "${{ env.NDK_INSTALL_DIR }}"
        # 设置环境变量
        echo "NDK_HOME=${{ env.NDK_INSTALL_DIR }}/android-ndk-r27b" >> $GITHUB_ENV

    - name: Verify NDK installation
      run: |
        if [ ! -d "$NDK_HOME" ]; then
          echo "❌ NDK installation failed!"
          ls -la "${{ env.NDK_INSTALL_DIR }}"
          exit 1
        fi
        echo "NDK path verified: $NDK_HOME"

    - name: Set up build environment
      run: |
        mkdir -p ${{ env.ANDROID_BUILD_DIR }}/{logs,outputs}
        chmod +x build_for_android.sh

    - name: Build all ABIs
      env:
        ABIS: "arm64-v8a armeabi-v7a x86_64 x86"
      run: |
        echo "▶️ Building..."
        NDK_HOME=${{ env.NDK_HOME }} \
        API_LEVEL=${{ github.event.inputs.API_LEVEL }} \
        OUTPUT_DIR="${{ env.ANDROID_BUILD_DIR }}/outputs" \
        LOG_DIR="${{ env.ANDROID_BUILD_DIR }}/logs" \
        ./build_for_android.sh --no-log-file
    - name: Package artifacts
      run: |
        cd ${{ env.ANDROID_BUILD_DIR }}
        tar -czvf android_build-v${{ github.event.inputs.API_LEVEL }}.tar.gz *

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: android_build-ndk${{ env.NDK_VERSION }}-api${{ github.event.inputs.API_LEVEL }}
        path: ${{ env.ANDROID_BUILD_DIR }}/android_build-v${{ github.event.inputs.API_LEVEL }}.tar.gz

    - name: Clean workspace
      if: always()
      run: |
        rm -rf ${{ env.ANDROID_BUILD_DIR }}/*
        rm -rf "${{ env.NDK_INSTALL_DIR }}"
